# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  server:
    container_name: server
    image: docker-setup:v1
    environment:
      NAME: Boot
    # build:
    #   context: '.'
    #   target: base
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/app/src
    networks:
      - test_vm
  server2:
    container_name: server2
    image: docker-setup:v2
    environment:
      NAME: Heels
    # build:
    #   context: '.'
    #   target: base
    expose:
      - 3000
    networks:
      - test_vm
networks:
  test_vm:
    name: test_vm
    driver: bridge